---
- name: zabbix
  box: 4linux/ubuntu16.04
  hostname: zabbix
  ipaddress: 192.168.99.10
  memory: 1536
  cpus: 1
  provision: provision/ansible/zabbix.yaml

- name: graylog
  box: 4linux/ubuntu16.04
  hostname: graylog
  ipaddress: 192.168.99.11
  memory: 2048
  cpus: 1
  provision: provision/ansible/graylog.yaml

- name: prometheus
  box: 4linux/centos7
  hostname: prometheus
  ipaddress: 192.168.99.12
  memory: 1536
  cpus: 1
  provision: provision/ansible/prometheus.yaml

- name: 4flix
  box: 4linux/centos7
  hostname: 4flix
  ipaddress: 192.168.99.13
  memory: 2048
  cpus: 1
  provision: provision/ansible/4flix.yaml
